name: Build Resume PDF

on:
  push:
    paths:
      - "resume/main.tex"   # Run only when main.tex is modified
  workflow_dispatch:        # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install LaTeX
      run: sudo apt update && sudo apt install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra

    - name: Compile PDF
      run: |
        cd resume
        pdflatex main.tex

    - name: Upload PDF to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume/main.pdf
